# Generated by Django 4.1.10 on 2023-11-13 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bemestar', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bemestar',
            options={'managed': False},
        ),
    ]
