# Generated by Django 4.1.10 on 2023-11-13 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bemestar', '0002_alter_bemestar_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='bemestar',
            table='entities_entity',
        ),
    ]
